# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forgotPassword.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_forgotPasswordPage(object):
    def setupUi(self, forgotPasswordPage):
        forgotPasswordPage.setObjectName("forgotPasswordPage")
        forgotPasswordPage.resize(585, 804)
        forgotPasswordPage.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(forgotPasswordPage)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 40, 521, 701))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 166);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.lblusername = QtWidgets.QLabel(self.frame)
        self.lblusername.setGeometry(QtCore.QRect(210, 220, 151, 16))
        self.lblusername.setStyleSheet("font: 75 17pt \"MS Serif\";")
        self.lblusername.setObjectName("lblusername")
        self.btnclear = QtWidgets.QPushButton(self.frame)
        self.btnclear.setGeometry(QtCore.QRect(290, 450, 111, 41))
        self.btnclear.setObjectName("btnclear")
        self.lblsecurityQuestion = QtWidgets.QLabel(self.frame)
        self.lblsecurityQuestion.setGeometry(QtCore.QRect(80, 280, 331, 21))
        self.lblsecurityQuestion.setStyleSheet("font: 75 17pt \"MS Serif\";")
        self.lblsecurityQuestion.setObjectName("lblsecurityQuestion")
        self.btnsubmit = QtWidgets.QPushButton(self.frame)
        self.btnsubmit.setGeometry(QtCore.QRect(90, 450, 111, 41))
        self.btnsubmit.setObjectName("btnsubmit")
        self.btnback = QtWidgets.QPushButton(self.frame)
        self.btnback.setGeometry(QtCore.QRect(90, 560, 111, 41))
        self.btnback.setObjectName("btnback")
        self.lbltitle = QtWidgets.QLabel(self.frame)
        self.lbltitle.setGeometry(QtCore.QRect(20, 10, 351, 71))
        self.lbltitle.setStyleSheet("font: 75 48pt \"Rockwell Condensed\";")
        self.lbltitle.setObjectName("lbltitle")
        self.lbllogo = QtWidgets.QLabel(self.frame)
        self.lbllogo.setGeometry(QtCore.QRect(360, 10, 151, 171))
        self.lbllogo.setText("")
        self.lbllogo.setPixmap(QtGui.QPixmap("Images/Logo.png"))
        self.lbllogo.setScaledContents(True)
        self.lbllogo.setObjectName("lbllogo")
        self.txtsecurityAnswer = QtWidgets.QLineEdit(self.frame)
        self.txtsecurityAnswer.setGeometry(QtCore.QRect(92, 329, 321, 31))
        self.txtsecurityAnswer.setObjectName("txtsecurityAnswer")
        forgotPasswordPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(forgotPasswordPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 585, 21))
        self.menubar.setObjectName("menubar")
        forgotPasswordPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(forgotPasswordPage)
        self.statusbar.setObjectName("statusbar")
        forgotPasswordPage.setStatusBar(self.statusbar)

        self.retranslateUi(forgotPasswordPage)
        QtCore.QMetaObject.connectSlotsByName(forgotPasswordPage)

    def retranslateUi(self, forgotPasswordPage):
        _translate = QtCore.QCoreApplication.translate
        forgotPasswordPage.setWindowTitle(_translate("forgotPasswordPage", "MainWindow"))
        self.lblusername.setText(_translate("forgotPasswordPage", "Username"))
        self.btnclear.setText(_translate("forgotPasswordPage", "Clear"))
        self.lblsecurityQuestion.setText(_translate("forgotPasswordPage", "Security Question:"))
        self.btnsubmit.setText(_translate("forgotPasswordPage", "Submit"))
        self.btnback.setText(_translate("forgotPasswordPage", "Back"))
        self.lbltitle.setText(_translate("forgotPasswordPage", "Forgot Password Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    forgotPasswordPage = QtWidgets.QMainWindow()
    ui = Ui_forgotPasswordPage()
    ui.setupUi(forgotPasswordPage)
    forgotPasswordPage.show()
    sys.exit(app.exec_())
