# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginPage(object):
    def setupUi(self, loginPage):
        loginPage.setObjectName("loginPage")
        loginPage.resize(581, 803)
        loginPage.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(loginPage)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 30, 521, 701))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 166);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.lblusername = QtWidgets.QLabel(self.frame)
        self.lblusername.setGeometry(QtCore.QRect(80, 220, 151, 16))
        self.lblusername.setStyleSheet("font: 75 17pt \"MS Serif\";")
        self.lblusername.setObjectName("lblusername")
        self.txtusername = QtWidgets.QLineEdit(self.frame)
        self.txtusername.setGeometry(QtCore.QRect(300, 220, 113, 20))
        self.txtusername.setObjectName("txtusername")
        self.txtpassword = QtWidgets.QLineEdit(self.frame)
        self.txtpassword.setGeometry(QtCore.QRect(300, 280, 113, 20))
        self.txtpassword.setText("")
        self.txtpassword.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtpassword.setObjectName("txtpassword")
        self.btnclear = QtWidgets.QPushButton(self.frame)
        self.btnclear.setGeometry(QtCore.QRect(100, 440, 111, 41))
        self.btnclear.setObjectName("btnclear")
        self.lblpassword = QtWidgets.QLabel(self.frame)
        self.lblpassword.setGeometry(QtCore.QRect(80, 280, 151, 16))
        self.lblpassword.setStyleSheet("font: 75 17pt \"MS Serif\";")
        self.lblpassword.setObjectName("lblpassword")
        self.btnsubmit = QtWidgets.QPushButton(self.frame)
        self.btnsubmit.setGeometry(QtCore.QRect(100, 550, 111, 41))
        self.btnsubmit.setObjectName("btnsubmit")
        self.btnforgotPassword = QtWidgets.QPushButton(self.frame)
        self.btnforgotPassword.setGeometry(QtCore.QRect(280, 440, 111, 41))
        self.btnforgotPassword.setObjectName("btnforgotPassword")
        self.btnregister = QtWidgets.QPushButton(self.frame)
        self.btnregister.setGeometry(QtCore.QRect(280, 550, 111, 41))
        self.btnregister.setObjectName("btnregister")
        self.lbltitle = QtWidgets.QLabel(self.frame)
        self.lbltitle.setGeometry(QtCore.QRect(20, 10, 261, 71))
        self.lbltitle.setStyleSheet("font: 75 48pt \"Rockwell Condensed\";")
        self.lbltitle.setObjectName("lbltitle")
        self.lbllogo = QtWidgets.QLabel(self.frame)
        self.lbllogo.setGeometry(QtCore.QRect(360, 10, 151, 171))
        self.lbllogo.setText("")
        self.lbllogo.setPixmap(QtGui.QPixmap("Images/Logo.png"))
        self.lbllogo.setScaledContents(True)
        self.lbllogo.setObjectName("lbllogo")
        loginPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(loginPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 581, 21))
        self.menubar.setObjectName("menubar")
        loginPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(loginPage)
        self.statusbar.setObjectName("statusbar")
        loginPage.setStatusBar(self.statusbar)

        self.retranslateUi(loginPage)
        QtCore.QMetaObject.connectSlotsByName(loginPage)

    def retranslateUi(self, loginPage):
        _translate = QtCore.QCoreApplication.translate
        loginPage.setWindowTitle(_translate("loginPage", "MainWindow"))
        self.lblusername.setText(_translate("loginPage", "Username:"))
        self.btnclear.setText(_translate("loginPage", "Clear"))
        self.lblpassword.setText(_translate("loginPage", "Password:"))
        self.btnsubmit.setText(_translate("loginPage", "Submit"))
        self.btnforgotPassword.setText(_translate("loginPage", "Forgot Password"))
        self.btnregister.setText(_translate("loginPage", "Register"))
        self.lbltitle.setText(_translate("loginPage", "Login Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginPage = QtWidgets.QMainWindow()
    ui = Ui_loginPage()
    ui.setupUi(loginPage)
    loginPage.show()
    sys.exit(app.exec_())
