# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_registerPage(object):
    def setupUi(self, registerPage):
        registerPage.setObjectName("registerPage")
        registerPage.resize(587, 803)
        registerPage.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(registerPage)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 30, 521, 701))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 166);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.lblname = QtWidgets.QLabel(self.frame)
        self.lblname.setGeometry(QtCore.QRect(80, 220, 151, 16))
        self.lblname.setStyleSheet("font: 75 17pt \"MS Serif\";")
        self.lblname.setObjectName("lblname")
        self.txtname = QtWidgets.QLineEdit(self.frame)
        self.txtname.setGeometry(QtCore.QRect(300, 220, 113, 20))
        self.txtname.setObjectName("txtname")
        self.txtusername = QtWidgets.QLineEdit(self.frame)
        self.txtusername.setGeometry(QtCore.QRect(300, 280, 113, 20))
        self.txtusername.setObjectName("txtusername")
        self.btnclear = QtWidgets.QPushButton(self.frame)
        self.btnclear.setGeometry(QtCore.QRect(290, 540, 111, 41))
        self.btnclear.setObjectName("btnclear")
        self.lblusername = QtWidgets.QLabel(self.frame)
        self.lblusername.setGeometry(QtCore.QRect(80, 280, 151, 16))
        self.lblusername.setStyleSheet("font: 75 17pt \"MS Serif\";")
        self.lblusername.setObjectName("lblusername")
        self.btnsubmit = QtWidgets.QPushButton(self.frame)
        self.btnsubmit.setGeometry(QtCore.QRect(90, 540, 111, 41))
        self.btnsubmit.setObjectName("btnsubmit")
        self.btnlogin = QtWidgets.QPushButton(self.frame)
        self.btnlogin.setGeometry(QtCore.QRect(290, 610, 111, 41))
        self.btnlogin.setObjectName("btnlogin")
        self.lbltitle = QtWidgets.QLabel(self.frame)
        self.lbltitle.setGeometry(QtCore.QRect(20, 10, 291, 71))
        self.lbltitle.setStyleSheet("font: 75 48pt \"Rockwell Condensed\";")
        self.lbltitle.setObjectName("lbltitle")
        self.lbllogo = QtWidgets.QLabel(self.frame)
        self.lbllogo.setGeometry(QtCore.QRect(360, 10, 151, 171))
        self.lbllogo.setText("")
        self.lbllogo.setPixmap(QtGui.QPixmap("Images/Logo.png"))
        self.lbllogo.setScaledContents(True)
        self.lbllogo.setObjectName("lbllogo")
        self.lblpassword = QtWidgets.QLabel(self.frame)
        self.lblpassword.setGeometry(QtCore.QRect(80, 340, 151, 16))
        self.lblpassword.setStyleSheet("font: 75 17pt \"MS Serif\";")
        self.lblpassword.setObjectName("lblpassword")
        self.txtpassword = QtWidgets.QLineEdit(self.frame)
        self.txtpassword.setGeometry(QtCore.QRect(300, 340, 113, 20))
        self.txtpassword.setObjectName("txtpassword")
        self.cmbsecurityAnswer = QtWidgets.QComboBox(self.frame)
        self.cmbsecurityAnswer.setGeometry(QtCore.QRect(70, 400, 361, 22))
        self.cmbsecurityAnswer.setEditable(False)
        self.cmbsecurityAnswer.setObjectName("cmbsecurityAnswer")
        self.cmbsecurityAnswer.addItem("")
        self.cmbsecurityAnswer.addItem("")
        self.cmbsecurityAnswer.addItem("")
        self.cmbsecurityAnswer.addItem("")
        self.txtsecurityAnswer = QtWidgets.QLineEdit(self.frame)
        self.txtsecurityAnswer.setGeometry(QtCore.QRect(90, 450, 331, 31))
        self.txtsecurityAnswer.setObjectName("txtsecurityAnswer")
        registerPage.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(registerPage)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 587, 21))
        self.menubar.setObjectName("menubar")
        registerPage.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(registerPage)
        self.statusbar.setObjectName("statusbar")
        registerPage.setStatusBar(self.statusbar)

        self.retranslateUi(registerPage)
        QtCore.QMetaObject.connectSlotsByName(registerPage)
        
    def retranslateUi(self, registerPage):
        _translate = QtCore.QCoreApplication.translate
        registerPage.setWindowTitle(_translate("registerPage", "MainWindow"))
        self.lblname.setText(_translate("registerPage", "Name:"))
        self.btnclear.setText(_translate("registerPage", "Clear"))
        self.lblusername.setText(_translate("registerPage", "Username:"))
        self.btnsubmit.setText(_translate("registerPage", "Submit"))
        self.btnlogin.setText(_translate("registerPage", "Login"))
        self.lbltitle.setText(_translate("registerPage", "Register Page"))
        self.lblpassword.setText(_translate("registerPage", "Password:"))
        self.cmbsecurityAnswer.setItemText(0, _translate("registerPage", "Security Question:"))
        self.cmbsecurityAnswer.setItemText(1, _translate("registerPage", "What was the name of your first pet?"))
        self.cmbsecurityAnswer.setItemText(2, _translate("registerPage", "What city were you born in?"))
        self.cmbsecurityAnswer.setItemText(3, _translate("registerPage", "What is your favourite food?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    registerPage = QtWidgets.QMainWindow()
    ui = Ui_registerPage()
    ui.setupUi(registerPage)
    registerPage.show()
    sys.exit(app.exec_())
